from Grafos.Grafo import *

def main():
    G=Grafo()
    """G.ingresarvertice("1")
    G.ingresarvertice("2")
    G.ingresarvertice("3")
    G.ingresarvertice("4")
    G.ingresarvertice("5")
    G.ingresarvertice("6")
    G.ingresarvertice("7")
    G.ingresarvertice("8")
    G.ingresarvertice("9")
    G.ingresarvertice("10")"""
    G.ingresarvertice("Silvestre")
    G.ingresarvertice("Tazmania")
    G.ingresarvertice("Yayita")
    G.ingresarvertice("Coyote")
    G.ingresarvertice("Piolin")
    G.ingresarvertice("Bunny")
    G.ingresarvertice("Popeye")
    G.ingresarvertice("Marvin")
    G.ingresarvertice("Correcaminos")
    """G.ingresarvertice("A")
    G.ingresarvertice("B")
    G.ingresarvertice("C")
    G.ingresarvertice("D")
    G.ingresarvertice("E")
    G.ingresarvertice("F")
    G.ingresarvertice("G")
    G.ingresararista('A', 'B', 7, False)
    G.ingresararista('A', 'D', 5, False)
    G.ingresararista('B', 'D', 9, False)
    G.ingresararista('B', 'C', 8, False)
    G.ingresararista('C', 'E', 5, False)
    G.ingresararista('B', 'E', 7, False)
    G.ingresararista('D', 'E', 15, False)
    G.ingresararista('D', 'F', 6, False)
    G.ingresararista('F', 'E', 8, False)
    G.ingresararista('F', 'G', 11, False)
    G.ingresararista('E', 'G', 9, False)"""
    """G.ingresararista('A', 'B', 2, False)
    G.ingresararista('A', 'C', 3, False)
    G.ingresararista('B', 'C', 1, False)
    G.ingresararista('B', 'D', 1, False)
    G.ingresararista('B', 'E', 4, False)
    G.ingresararista('C', 'F', 5, False)
    G.ingresararista('D', 'E', 1, False)
    G.ingresararista('F', 'E', 1, False)
    G.ingresararista('F', 'G', 1, False)"""
    G.ingresararista("Silvestre","Piolin",10,False)
    G.ingresararista("Silvestre", "Tazmania", 15, False)
    G.ingresararista("Piolin", "Popeye", 30, False)
    G.ingresararista("Yayita", "Piolin", 25, False)
    G.ingresararista("Yayita", "Tazmania", 16, False)
    G.ingresararista("Yayita", "Bunny", 22, False)
    G.ingresararista("Bunny", "Tazmania", 33, False)
    G.ingresararista("Coyote", "Tazmania", 21, False)
    G.ingresararista("Coyote", "Marvin", 58, False)
    G.ingresararista("Bunny", "Marvin", 2, False)
    G.ingresararista("Marvin", "Correcaminos", 44, False)
    G.ingresararista("Correcaminos", "Bunny", 60, False)
    G.ingresararista("Correcaminos", "Popeye", 5, False)
    """G.ingresararista("1", "8", 60, False)
    G.ingresararista("1", "2", 10, False)
    G.ingresararista("2", "7", 70, False)
    G.ingresararista("7", "8", 80, False)
    G.ingresararista("2", "3", 40, False)
    G.ingresararista("4", "9", 90, False)
    G.ingresararista("2", "4", 100, False)
    G.ingresararista("3", "5", 50, False)
    G.ingresararista("3", "6", 120, False)
    G.ingresararista("5", "4", 110, False)
    G.ingresararista("5", "6", 20, False)
    G.ingresararista("9", "6", 130, False)
    G.ingresararista("9", "10", 30, False)"""
    G.arbolprim("Popeye")
    G.Prim()



main()
